"""initial schema

Revision ID: 2988d21daabf
Revises: 
Create Date: 2026-08-21 20:19:43.966407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2988d21daabf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('met_value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'usda'"), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('food_name', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carbs_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fiber_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sugar_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('default_serving_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('source', 'external_id', name='uq_foods_source_external_id')
    )
    op.create_index('idx_foods_name_trgm', 'foods', [sa.literal_column('food_name gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.Text(), nullable=True),
    sa.Column('external_auth_id', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_level IN ('sedentary','light','moderate','active','very_active')", name='ck_users_activity_level'),
    sa.CheckConstraint("goal_type IN ('lose','maintain','gain')", name='ck_users_goal_type'),
    sa.CheckConstraint("sex IN ('male', 'female', 'other')", name='ck_users_sex'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'external_auth_id', name='uq_users_external_identity'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'food_id', name='uq_food_aliases_alias_food')
    )
    op.create_index('idx_food_aliases_alias_trgm', 'food_aliases', [sa.literal_column('alias gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.create_table('photo_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('raw_model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_target_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_target_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weight_logs_user_date', 'weight_logs', ['user_id', 'logged_at'], unique=False)
    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.Text(), nullable=False),
    sa.Column('meal_type', sa.Text(), nullable=False),
    sa.Column('food_name_raw', sa.Text(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('confidence_tier', sa.Text(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence_tier IN ('high','medium','low')", name='ck_food_entries_confidence_tier'),
    sa.CheckConstraint("entry_method IN ('manual','barcode','photo','chat')", name='ck_food_entries_entry_method'),
    sa.CheckConstraint("meal_type IN ('breakfast','lunch','dinner','snack')", name='ck_food_entries_meal_type'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_entries_user_date', 'food_entries', ['user_id', 'logged_date'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_history_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_description', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('food_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_entry_id'], ['food_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_scan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_scan_id', sa.Integer(), nullable=False),
    sa.Column('detected_name', sa.Text(), nullable=False),
    sa.Column('matched_food_id', sa.Integer(), nullable=True),
    sa.Column('estimated_quantity_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('confidence_tier', sa.Text(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resulting_entry_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("confidence_tier IN ('high','medium','low')", name='ck_photo_scan_items_confidence_tier'),
    sa.ForeignKeyConstraint(['matched_food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['photo_scan_id'], ['photo_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_entry_id'], ['food_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_scan_items')
    op.drop_table('meal_history_embeddings')
    op.drop_table('recipe_ingredients')
    op.drop_index('idx_food_entries_user_date', table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index('idx_weight_logs_user_date', table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_table('water_logs')
    op.drop_table('user_goals')
    op.drop_table('recipes')
    op.drop_table('photo_scans')
    op.drop_index('idx_food_aliases_alias_trgm', table_name='food_aliases', postgresql_using='gin')
    op.drop_table('food_aliases')
    op.drop_table('exercise_logs')
    op.drop_table('users')
    op.drop_index('idx_foods_name_trgm', table_name='foods', postgresql_using='gin')
    op.drop_table('foods')
    op.drop_table('exercise_types')
    # ### end Alembic commands ###
