"""add food data_type and food_portions

Revision ID: 6c0e3a2cb883
Revises: 2988d21daabf
Create Date: 2026-08-21 21:05:11.532045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e3a2cb883'
down_revision: Union[str, Sequence[str], None] = '2988d21daabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('modifier', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gram_weight', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'external_id', name='uq_food_portions_food_external')
    )
    op.create_index('idx_food_portions_food_id', 'food_portions', ['food_id'], unique=False)
    op.add_column('foods', sa.Column('data_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'data_type')
    op.drop_index('idx_food_portions_food_id', table_name='food_portions')
    op.drop_table('food_portions')
    # ### end Alembic commands ###
